#!/usr/bin/python

import iniparse
import sys

try:
  cfgfile=sys.argv[1]
  section=sys.argv[2]
  parameter=sys.argv[3]
  value=sys.argv[4]
except:
  print sys.argv[0]+" config_file section parameter value"
  sys.exit(1)

conf=iniparse.ConfigParser()
conf.read(cfgfile)
conf.set(section, parameter, value)

fp=open(cfgfile,"w")
conf.write(fp)
fp.close()

